plugins {
    id 'java'
    id 'org.gretty' version '4.1.6'
    id 'idea'
    id 'groovy'
    id 'io.github.joselion.pretty-jupiter' version '3.5.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

ext['springBootVer'] = '3.3.2'

repositories {
    mavenCentral()
}

gretty {
    springBootVersion = '3.3.2'
    springBoot = true
    servletContainer = 'jetty11'
    contextPath = ''
}

configurations {
    providedRuntime
}

dependencies {
    implementation(group: 'jakarta.xml.bind', name: 'jakarta.xml.bind-api', version: '4.0.2')
    implementation(group: 'jakarta.servlet', name:'jakarta.servlet-api', version:'6.1.0')

    // Spring
    implementation(group:'org.springframework.boot', name:'spring-boot-starter-data-jpa', version:"${springBootVer}")
    implementation(group:'org.springframework.boot', name:'spring-boot-starter-security', version:"${springBootVer}")
    implementation(group:'org.springframework.boot', name:'spring-boot-starter-validation', version:"${springBootVer}")
    implementation(group:'net.rakugakibox.spring.boot', name:'logback-access-spring-boot-starter', version:'2.11.0')

    implementation(group:'com.authy', name:'authy-java', version:'1.5.1')
    implementation(group:'com.twilio.sdk', name:'twilio', version:'10.8.0')
    implementation(group:'org.xerial', name:'sqlite-jdbc', version:'3.49.1.0')

    testImplementation(group: 'junit', name:'junit', version:'4.13.2')
    testImplementation(group:'org.springframework.boot', name:'spring-boot-starter-test', version:"${springBootVer}")
    // Groovy
    testImplementation (group: 'org.apache.groovy', name: 'groovy-all', version: '4.0.26', ext: 'pom')

    // Constraints
    constraints {
        implementation('org.json:json:20231013') {
          because("version defined in authy-java (transitive dependency) has vulnerabilities issues")
        }
    }

    // Spock
    testImplementation(group:'org.spockframework', name:'spock-core', version:'2.4-M6-groovy-4.0')
    testImplementation(group:'org.spockframework', name:'spock-spring', version:'2.4-M6-groovy-4.0')
    testRuntimeOnly(group:'cglib', name:'cglib-nodep', version:'3.3.0')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

test {
    useJUnitPlatform()
    reports {
        junitXml.required = false
        html.required = false
    }
    testLogging {
        exceptionFormat = "full"
    }
}
